// Imports from React
import React from 'react'

// Import stylesheet
import './TermsConditions.css'

// Imports from React-Bootstrap
import { Stack, Container, Row, Col } from 'react-bootstrap'

// AboutUs page payout
export const TermsConditions = () => {
  return (
    <div className='termsConditionsMainContainer'>
      <Stack gap={0}>
        <div className="lightSection">
            <Container fluid>
              <Row className="justify-content-md-center">
                <Col xs lg='10'>
                  <h1>Terms & Conditions</h1>
                  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin laoreet a augue eu eleifend. Quisque volutpat lorem velit, vitae porta diam luctus ut. Vestibulum malesuada lobortis neque, nec hendrerit nisl. Integer semper arcu quis ligula luctus venenatis. Donec laoreet risus vitae porttitor sodales. Vestibulum pulvinar, mauris at placerat sodales, eros lorem molestie metus, eu sagittis massa tellus quis sem. In pretium lacinia sagittis. Maecenas tincidunt ipsum ut euismod feugiat. Donec dictum justo metus, sit amet molestie felis porttitor nec. Nulla facilisi. Duis tempor quam in quam gravida, non maximus tortor vestibulum.</p>
                  <p>Nam hendrerit erat diam. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In in leo euismod, sollicitudin sapien non, bibendum justo. Integer iaculis lobortis sapien, sed dictum libero congue vitae. Nulla a laoreet nisl, a tempor est. Pellentesque finibus tortor et augue molestie tempus. Aliquam in iaculis purus. Duis quis pretium velit, id accumsan lectus. Maecenas malesuada ipsum tempus leo commodo, eget tempor arcu porta. Fusce posuere malesuada tellus id porttitor. Nulla eu auctor purus.</p>
                  <p>Curabitur eget nibh eget mauris porta tempus. Donec non nibh et tortor congue vestibulum. Vestibulum sodales rutrum tincidunt. Praesent mollis, erat in porttitor dignissim, nunc ipsum ornare mauris, id blandit velit tortor dignissim nisl. Aliquam erat volutpat. Ut dignissim mi nunc, non elementum felis consectetur at. Curabitur convallis risus eu felis gravida venenatis. Nullam gravida bibendum felis quis eleifend. Cras quis enim in ante dapibus scelerisque id eu diam. Nullam risus tellus, semper a enim at, gravida convallis justo. Curabitur ut pellentesque nibh.</p>
                  <p>Nunc non dolor iaculis, cursus quam ac, luctus dui. Ut interdum orci eu est venenatis malesuada. Vivamus semper aliquet eros, fermentum dictum lacus accumsan et. Fusce tincidunt, lectus ullamcorper laoreet varius, lacus neque sagittis nulla, et auctor mauris velit non dui. Curabitur ut nunc nec velit elementum imperdiet ac sit amet nunc. Nulla consectetur tellus eget leo dignissim ultrices. Sed euismod, nunc eget finibus iaculis, turpis purus blandit ipsum, at lacinia ex neque a ipsum. Quisque accumsan ex et elit fermentum convallis. Mauris hendrerit ac velit et pretium. Ut maximus tortor vitae sem aliquet, eleifend scelerisque lacus fringilla.</p>
                  <p>Sed vestibulum mauris at accumsan venenatis. Donec a diam orci. Vivamus rutrum turpis nibh, sodales congue orci varius non. Suspendisse potenti. Aenean quam purus, euismod vitae metus et, ultrices iaculis sem. Vestibulum a rutrum leo. Donec viverra, ipsum tempor scelerisque rhoncus, purus ante feugiat ligula, a bibendum felis nulla et dolor. Nullam ac ex ex. Praesent maximus orci turpis, ornare auctor nunc tempor et. Sed in eros porttitor, porta mi a, imperdiet dui. Mauris rutrum orci et velit pulvinar dictum. Praesent sollicitudin, leo sit amet lacinia mattis, dolor neque lobortis velit, nec mattis odio urna quis ipsum.</p>
                  <p>In sed libero nec eros commodo efficitur vel vitae eros. Maecenas vehicula rutrum lorem quis ullamcorper. Morbi finibus efficitur auctor. Fusce lobortis molestie nulla vel tempor. In tincidunt, ex in dapibus sagittis, risus odio efficitur lectus, non gravida leo neque eu arcu. Sed vestibulum non magna in pretium. Nullam ac pellentesque est. Mauris at fermentum dolor, ut dapibus nisl. Vestibulum tempor leo et leo sodales, ac viverra odio egestas. Vivamus felis velit, viverra id accumsan eu, facilisis non elit. Phasellus sit amet leo nec magna tristique ultricies in id tellus. Sed ex justo, viverra eget libero id, porttitor venenatis tortor. Morbi malesuada urna nec lectus ornare finibus. In placerat dolor ac tortor elementum, id interdum tellus elementum.</p>
                  <p>Proin venenatis venenatis luctus. Aenean vehicula bibendum ultricies. Aliquam convallis diam quis feugiat pretium. Maecenas porta convallis justo sit amet finibus. Cras vehicula, dui id malesuada porttitor, felis erat consectetur sem, vitae malesuada arcu magna ac lectus. Praesent at laoreet nisi, placerat finibus sapien. Aenean id ex semper, condimentum massa non, auctor diam. Nunc semper, metus non tempus tempus, elit nisl eleifend ex, ut euismod lacus nisi et neque. Nam mollis, sem quis pellentesque dignissim, massa purus efficitur neque, vel aliquet lacus tellus ut leo. Phasellus ut varius augue. Quisque ornare egestas odio quis ullamcorper.</p>
                  <p>Cras sem ipsum, gravida vel tellus lacinia, pretium semper purus. Aliquam vestibulum, magna sit amet efficitur iaculis, mi neque imperdiet lorem, vitae congue tortor lorem eget felis. Morbi suscipit ultricies dictum. Cras aliquet sed lacus eget scelerisque. Aliquam quis lacus a lectus mollis mattis id quis orci. Nunc est nisl, fringilla et bibendum ac, ornare quis ipsum. Curabitur varius ante sed odio malesuada, vitae mollis arcu facilisis. Morbi luctus, leo in tincidunt placerat, nisi dui hendrerit magna, at congue lorem risus at leo.</p>
                  <p>Nam quam lacus, porttitor et pulvinar vel, sollicitudin eu ligula. In a pharetra lectus. Phasellus gravida enim sapien, et commodo justo tincidunt a. Etiam luctus odio in tristique maximus. Suspendisse potenti. Fusce scelerisque facilisis tincidunt. Nullam luctus, turpis at accumsan aliquam, libero magna ultrices mi, non tristique dui turpis fermentum nulla. Vivamus dignissim ullamcorper convallis. Etiam sit amet consectetur justo. Curabitur ante magna, facilisis nec sagittis id, cursus a quam. Aenean id lectus ligula. Aenean in sagittis diam, at vulputate enim. Vivamus rhoncus mi pretium, condimentum diam eget, viverra arcu. Morbi porta urna id ante placerat, non commodo diam vehicula. Sed tincidunt nulla at porttitor tempus.</p>
                  <p>Ut lorem leo, dapibus nec dolor ac, iaculis aliquet nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Praesent malesuada augue vel sodales vestibulum. Sed egestas ultrices consequat. Mauris vel feugiat tortor. Nulla pulvinar ante nec interdum egestas. Nullam id leo lobortis metus elementum hendrerit. Donec placerat eu metus id iaculis. Pellentesque sollicitudin mi eu sodales vehicula. Cras ut mi ultrices, vestibulum ex at, gravida sem. Quisque vel pharetra risus, sit amet varius felis. Sed venenatis nunc quis dolor pretium, nec laoreet urna pharetra. Duis varius eget tellus quis fermentum. Curabitur eleifend ante in mi facilisis, non bibendum leo consequat.</p>
                  <p>Cras pharetra dapibus neque, vitae volutpat dolor congue et. Cras ut accumsan nulla. Nam nec vehicula diam, consectetur efficitur nulla. Vestibulum porttitor, dolor at faucibus pulvinar, enim turpis elementum nisl, et mollis mi augue auctor nisl. Integer non felis nec erat aliquam ornare. Quisque vel tortor volutpat, semper tortor et, sagittis quam. Interdum et malesuada fames ac ante ipsum primis in faucibus. Cras fringilla tortor et hendrerit aliquet.</p>
                  <p>Morbi id vehicula augue. Vestibulum euismod metus nec magna efficitur, sit amet congue nisl dapibus. Cras lobortis a diam id efficitur. Etiam semper elit scelerisque nibh congue porttitor. Mauris ut fringilla nisl, vitae finibus nibh. Vestibulum dui dui, cursus volutpat elit eget, venenatis dictum erat. Etiam lacus nisl, rutrum ut maximus vitae, bibendum quis sem. Donec facilisis risus et nulla blandit blandit. Suspendisse cursus fermentum urna, vitae ornare lectus consequat sit amet. Donec id feugiat massa, sit amet rhoncus quam.</p>
                </Col>
              </Row>
            </Container>
        </div>
      </Stack>
    </div>
  )
}
